<footer>
    <div class="bottom">
        <nav>
            <ul>
                <li><a href="https://www.swinburne.edu.au/study/courses/units/Creating-Web-Applications-COS10011/local"><img src="images/description_icon.svg" alt="swinburne">COS60004 Creating Web Applications</a></li>
                <li><a href="https://swinburne.edu.au"><img src="images/copyright_icon.svg" alt="swinburne university">Swinburne University of Technology</a></li>
                <li><a href="mailto:104020390@student.swin.edu.au"><img src="images/email_icon.svg" alt="email">Sang Vo</a></li>
            </ul>
        </nav>
    </div>
</footer>