<header> 
    <div class="container">
        <h1>ASP.NET</h1>
        <nav> 
            <ul>
                <li><a href="index.php"><img src="images/home_icon.svg" alt="home">Home</a></li>
                <li><a href="topic.php"><img src="images/rocket_icon.svg" alt="topic">Info</a></li>
                <li><a href="quiz.php"><img src="images/quiz_icon.svg" alt="quiz">Quiz</a></li>
                <li><a href="user_login.php"><img src="images/search_icon.svg" alt="login page">Queries</a></li>
                <li><a href="enhancements.php"><img src="images/enhancement_icon.svg" alt="enhancements">Enhancements</a></li>
                <li><a href="enhancements2.php"><img src="images/enhancement_icon.svg" alt="enhancements2">Enhancements 2</a></li>
                <li><a href="phpenhancements.php"><img src="images/enhancement_icon.svg" alt="phpenhancements">PHP</a></li>
            </ul>
        </nav>
    </div>
</header> 