<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Introductory Home Page" />
    <meta name="keywords" content="HTML, CSS, ASP.NET" />
    <meta name="author" content="Sang Vo"  />

    <link href ="styles/style.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    
    <title>ASP.NET</title>
</head>

<body>
<?php
include("header.inc")  
?>

<section id="micro">
&nbsp;<a href="https://www.microsoft.com/en-au/"><img src="images/microsoft_logo.png" width="600" height="600" alt="microsoft_logo"></a>
</section>

<section id="info_1">
<h2>Created by Microsoft</h2> 
<h2>FREE</h2>
<h2>Open-source web framework</h2>
<h2>Create web applications easily on .NET</h2> 
</section>

<section id = "info_2">
<h2>ASP.Net is a free web framework for building modern web applications using:</h2>
<ul>
    <li>HTML</li>
    <li>CSS</li>
    <li>JavaScript</li>
    <li>C#</li>
</ul>
</section>

<h3>Compatible with macOS, Windows, and Linux</h3>
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <figure><img src="images/comp.png" usemap="#image-map"><figcaption>Click on the logos!</figcaption></figure>
        <div class="osys_index">
            <map name="image-map">
                <area target="circle" alt="macOS" title="macOS" href="https://www.apple.com/mac/" coords="164,117,44" shape="circle">
                <area target="poly" alt="Windows" title="Windows" href="https://www.microsoft.com/en-au/windows" coords="109,41,108,119,42,104,43,52,75,46" shape="poly">
                <area target="circle" alt="Linux" title="Linux" href="https://www.linux.org" coords="86,171,37" shape="circle">
            </map>
        </div>

<?php
include("footer.inc")  
?>
</body>


</html>