<header> 
    <div class="container">
        <h1>SEARCH</h1>
        <nav> 
            <ul>
                <li><a href="index.php"><img src="images/home_icon.svg" alt="home">Home</a></li>
                <li><a href="list_all.php"><img src="images/rocket_icon.svg" alt="list all student results">All Attempts</a></li>
                <li><a href="list_student.php"><img src="images/rocket_icon.svg" alt="list particular student results">Search</a></li>
                <li><a href="list_100.php"><img src="images/rocket_icon.svg" alt="list all student results who got 100% first attempt">100%</a></li>
                <li><a href="list_50.php"><img src="images/rocket_icon.svg" alt="list all student results who less than 50% on second attempt"> <50%</a></li>
                <li><a href="list_delete.php"><img src="images/rocket_icon.svg" alt="deletes all attempts for particular student">Delete Attempts</a></li>
                <li><a href="list_change.php"><img src="images/rocket_icon.svg" alt="change the score for a quiz attempt">Change Score</a></li>
            </ul>
        </nav>
    </div>
</header> 