<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="description" content="Topic description page" />
    <meta name="keywords" content="HTML, CSS, ASP.NET" />
    <meta name="author" content="Sang Vo"  />

    <link href ="styles/style.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    
    <title>Dive Deeper into ASP.NET</title>
</head>

<body>
<?php
include("header.inc")  
?>  
    
<article> 
    <section id="explain_1">
        <h1>What is ASP.NET?</h1>
        <br><br><br>
        <p>ASP.NET is an open-source web application framework based on C#. It is used to build web applications on the .NET framework.</p>
        <ul>
            <li>1998 – Classic ASP (Active Server Pages) was released by Microsoft as their first server-side scripting language</li>
            <li>2002 – Version 1.0 of ASP.Net was released by Microsoft in 2002 and was the successor of Classic ASP</li>
        </ul>
        <figure><a href="https://dotnet.microsoft.com/en-us/"><img src="images/aspnet-laptop.png" width="225" height="150"></a><figcaption>Click the screen to learn more!</figcaption></figure>
    </section>
 
    <section id="explain_2">
        <h1>3 Reasons why ASP.NET is great!</h1>
        <br><br><br>
        <ol>
            <li>It is a lot simpler to maintain & update, which results in an affordable and highly-competent framework</li>
            <li>ASP.NET is created and supported by Microsoft, being one of the leading companies in the globe there is higher level of safety and security assurance for users</li>
            <li>It offers customization in the data storage where you can easily distinguish identity information storage and security information</li>
        </ol>
        <br><h2>Are you convinced yet?</h2>
    </section>

    <section id="explain_3">
        <h1>Compatibility</h1>
        <br><br><br>
        <h2>Programming models</h2>
        <ul>
            <li>Classic ASP</li>
            <li>ASP.NET Web Forms</li>
            <li>ASP.NET MVC</li>
            <li>ASP.NET Web Pages</li>
            <li>ASP.NET API</li>
            <li>ASP.NET Core</li>
        </ul>
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <figure><img src="images/comp.png" usemap="#image-map"><figcaption>Click on the logos!</figcaption></figure>
        <div class="osys_topic">
            <map name="image-map">
                <area target="circle" alt="macOS" title="macOS" href="https://www.apple.com/mac/" coords="164,117,44" shape="circle">
                <area target="poly" alt="Windows" title="Windows" href="https://www.microsoft.com/en-au/windows" coords="109,41,108,119,42,104,43,52,75,46" shape="poly">
                <area target="circle" alt="Linux" title="Linux" href="https://www.linux.org" coords="86,171,37" shape="circle">
            </map>
        </div>
    </section>

    <section id="tech_logos">
        <ul>
            <div class="figure1">
            <figure><li><a href="https://dotnet.microsoft.com/en-us/apps/aspnet"><img src="images/ASP_logo.png" width="200" height="200"></a></li><figcaption>ASP.NET</figcaption></figure>
            </div>
            <div class="figure2">
            <figure><li><a href="https://nodejs.org/en/"><img src="images/nodejs_logo.png" width="200" height="200"></a></li><figcaption>Node.JS</figcaption></figure>
            </div>  
            <div class="figure3">
            <figure><li><a href="https://www.php.net"><img src="images/php_logo.png" width="200" height="200"></a></li><figcaption>PHP</figcaption></figure>
            </div>
        </ul>
    </section>

    <section id="tables">
        <div class="comparison_h">
        <h2>ASP.NET compared to other technologies</h2>
        </div>  
        <table>
            <tr>    
                <th>&nbsp;</th>
                <th>ASP.NET</th> 
                <th>Node.JS</th>
                <th>PHP</th>
            </tr>   
            <tr>
                <th>Brief Description</th>
                <td>Open-source web applications on the .NET framework built by Microsoft</td> 
                <td>Open-source, cross-platform, back-end, executes JavaScript code outside a web browser</td>
                <td>Open source scripting language for web development, can be embedded into HTML</td>
            </tr>
            <tr>
                <th>Earliest Version</th>
                <td>January, 2002</td> 
                <td>May, 2009</td>
                <td>June, 1995</td>
            </tr>
            <tr>
                <th>Latest Version</th>
                <td>[6.0] February, 2022</td> 
                <td>[17.8.0] March, 2022</td>
                <td>[8.1.4] March, 2022</td>
            </tr>
            <tr>
                <th>Primary Coding Language</th>
                <td>C#</td> 
                <td>JavaScript</td>
                <td>PHP</td>
            </tr>
            <tr>
                <th>Processing Model</th>
                <td>Synchronous, multi-threaded, blocking I/O</td> 
                <td>Asynchronous, single-thread non-blocking, I/O model</td>
                <td>Synchronous, multi-threaded, non-blocking, I/O model</td>
            </tr>
            <tr>
                <th>Industry Applications</th>
                <td>AccuWeather, Dell, Stackoverflow</td> 
                <td>NASA, Walmart, eBay, Uber</td>
                <td>Facebook, Wikipedia, Tumblr, Slack</td>
            </tr>
        </table>
    </section>
</article>

<?php
include("footer.inc")  
?>

</body>
</html>